### ISSUE TITLE
Quitar el Token 

### ISSUE THREAD

**Issue by fgjtam-dgtit-raul** [JuanRangel-FGJTam/DirectoryApi#40]
No mostrar el token en las sesiones del usuario

**Comment by JuanRangel-FGJTam** [comment]
Ya se removio el token de la vista de sesiones en este commit: JuanRangel-FGJTam/DirectorySite@9d42c14b8f99f096ab5ed73190b71234e32de0f6

En este cambio voy cambiar la respuestas de las sessiones para no retornar el token
