### ISSUE TITLE
Agregar nuevo endpoint en /procedures

### ISSUE THREAD

**Issue by fgjtam-dgtit-raul** [JuanRangel-FGJTam/DirectoryApi#5]
Agregar nuevo endpoint para actualizar los datos de los trámites del usuario como el status y observations.

**Comment by JuanRangel-FGJTam** [comment]
@fgjtam-dgtit-raul  Los campos que se pueden editar:
1. estatus
2. comentarios|observaciones
3. denuncia_id ??
